fe = input()
gb = input()
ics = input()
cp = input()

print("---Your Score---")
print("Foundation English: ",fe)
print("General Business: ",gb)
print("Introduction to Computer Systems: ",ics)
print("Computer Programming: ",cp)